#!/bin/bash
# Simple Fix - Restore Dashboard.tsx from backup
# Run this on your VPS: bash SIMPLE-FIX.sh

cd /var/www/hackfiles

echo "🔄 Restoring Dashboard.tsx from backup..."
cp client/src/pages/Dashboard.tsx.backup client/src/pages/Dashboard.tsx

echo "✅ Dashboard.tsx restored!"
echo ""
echo "Now I'll show you the exact lines to change manually..."
echo "See the instructions below:"
echo ""
echo "================================================"
echo "MANUAL CHANGES NEEDED IN Dashboard.tsx"
echo "================================================"
echo ""
echo "1. Find this line (around line 21):"
echo "   import { FolderPlus, Upload, LogOut, FolderOpen, Loader2, CheckSquare, Settings } from 'lucide-react';"
echo ""
echo "   Replace with:"
echo "   import { FolderPlus, Upload, LogOut, FolderOpen, Loader2, CheckSquare, Settings, Database } from 'lucide-react';"
echo ""
echo "2. Find these lines (around line 445-450):"
echo "   <DropdownMenuSeparator />"
echo "   {user?.isAdmin && ("
echo "     <DropdownMenuItem onClick={() => navigate('/admin')} data-testid=\"link-admin\">"
echo "       <Settings className=\"mr-2 h-4 w-4\" />"
echo "       Admin Dashboard"
echo "     </DropdownMenuItem>"
echo "   )}"
echo ""
echo "   Replace with:"
echo "   <DropdownMenuSeparator />"
echo "   {user?.isAdmin && ("
echo "     <>"
echo "       <DropdownMenuItem onClick={() => navigate('/admin')} data-testid=\"link-admin\">"
echo "         <Settings className=\"mr-2 h-4 w-4\" />"
echo "         Admin Dashboard"
echo "       </DropdownMenuItem>"
echo "       <DropdownMenuItem onClick={() => navigate('/s3-browser')} data-testid=\"link-s3-browser\">"
echo "         <Database className=\"mr-2 h-4 w-4\" />"
echo "         S3 Browser"
echo "       </DropdownMenuItem>"
echo "     </>"
echo "   )}"
echo ""
echo "================================================"
echo "That's it! Just TWO small changes."
echo "================================================"
